from dataclasses import dataclass
from typing import Dict, Any

class Event:
    """Base Event class."""
    pass

@dataclass
class MarketEvent(Event):
    """Triggered when new market price data arrives."""
    timestamp: str
    data: Dict[str, Dict[str,float]]
    type: str = "MARKET"

from dataclasses import dataclass
from typing import Dict, Any

class Event:
    """Base Event class."""
    pass

@dataclass
class MarketEvent(Event):
    """Triggered when new market price data arrives."""
    timestamp: str
    data: Dict[str, Dict[str, float]]
    type: str = "MARKET"

@dataclass
class SignalEvent(Event):
    """Generated by the Strategy class to signal buy/sell orders."""
    timestamp: str
    symbol_pair: tuple
    signal_type: str 
    z_score: float
    type: str = "SIGNAL"

@dataclass
class OrderEvent(Event):
    """Generated by Portfolio to send orders to Execution Handler."""
    timestamp: str
    symbol: str
    order_type: str
    quantity: int
    type: str = "ORDER"

@dataclass
class FillEvent(Event):
    """Encapsulates order execution details and price."""
    timestamp: str
    symbol: str
    quantity: int
    direction: str
    fill_cost: float
    type: str = "FILL"