from dataclasses import dataclass 
from typing import Dict, Any

class Event:
    """Base Event class."""
    pass

@dataclass
class MarketEvent(Event):
    """Triggered when new market price data arrives."""
    timestamp: str
    data: Dict[str, Dict[dtr, float]]
    type: str = "MARKET"

@dataclass
class SignalEvent(Event):
    """Generated by Strategy class to signal buy/sell orders."""
    timestamp: str
    symbol_pair: tuple
    signal_type: str # 'LONG_PAIR', 'SHORT_PAIR', or 'EXIT'
    z_score: float
    type: str = "SIGNAL"

@dataclass
class OrderEvent(Event):
    """Generated by Portfolio to send orders to Execution Handler."""
    timestamp: str
    symbol: str
    order_type: str  # 'BUY' or 'SELL'
    quantity: int
    type: str = "ORDER"

@dataclass
class FillEvent(Event):
    """Encapsulates order execution details, fill price, and transaction costs."""
    timestamp: str
    symbol: str
    quantity: int
    direction: str  # 'BUY' or 'SELL'
    fill_cost: float
    commission: float = 0.0
    slippage: float = 0.0
    type: str = "FILL"