import numpy as np
import collections
from dataclasses import dataclass
from events import Event, MarketEvent

@dataclass
class SignalEvent(Event):
    """Generated by the Strategy class to signal buy/sell orders."""
    timestamp: str
    symbol_pair: tuple
    signal_type: str
    z_score: float
    type: str = "SIGNAL"


class PairsStatArbStrategy:
    """
    Computes rolling Z-score between two assets (KO and PEP) and emits trading signals when thresholds are crossed.
    """
    def __init__(self, events_queue, pair=('KO', 'PEP'), window=30, entry_z=2.0, exit_z=0.5):
        self.events_queue = events_queue
        self.pair = pair
        self.window = window
        self.entry_z = entry_z
        self.exit_z = exit_z

        self.price_history = {pair[0]: collections.deque(maxlen=window),
                              pair[1]: collections.deque(maxlen=window)}
        self.in_position = False
        self.current_position = None  # 'LONG_PAIR' or 'SHORT_PAIR'

    def calculate_signals(self, event: MarketEvent):
        """Processes market data events to compute Z-Score and emit SignalEvents."""
        if event.type != "MARKET":
            return

        # 1. Update price queues
        for symbol in self.pair:
            if symbol in event.data:
                self.price_history[symbol].append(event.data[symbol]['close'])

        # Wait until we have enough historical bars for rolling calculations
        if len(self.price_history[self.pair[0]]) < self.window:
            return

        # 2. Calculate Spread (KO / PEP) and Z-Score
        prices_a = np.array(self.price_history[self.pair[0]])
        prices_b = np.array(self.price_history[self.pair[1]])
        spreads = prices_a / prices_b

        current_spread = spreads[-1]
        mean_spread = np.mean(spreads)
        std_spread = np.std(spreads)

        if std_spread == 0:
            return

        z_score = (current_spread - mean_spread) / std_spread

        # 3. Logic for Pair Entry & Exit Signals
        if not self.in_position:
            if z_score > self.entry_z:
                # Spread is too high -> Short asset A, Long asset B
                signal = SignalEvent(
                    timestamp=event.timestamp,
                    symbol_pair=self.pair,
                    signal_type="SHORT_PAIR",
                    z_score=z_score
                )
                self.events_queue.put(signal)
                self.in_position = True
                self.current_position = "SHORT_PAIR"

            elif z_score < -self.entry_z:
                # Spread is too low -> Long asset A, Short asset B
                signal = SignalEvent(
                    timestamp=event.timestamp,
                    symbol_pair=self.pair,
                    signal_type="LONG_PAIR",
                    z_score=z_score
                )
                self.events_queue.put(signal)
                self.in_position = True
                self.current_position = "LONG_PAIR"

        else:
            # Mean Reversion Exit Check
            if abs(z_score) < self.exit_z:
                signal = SignalEvent(
                    timestamp=event.timestamp,
                    symbol_pair=self.pair,
                    signal_type="EXIT",
                    z_score=z_score
                )
                self.events_queue.put(signal)
                self.in_position = False
                self.current_position = None